config/routes.rb
Rails.application.routes.draw do
  resources :books

  root 'books#index'

  get 'search', to: 'search#search'

end

app/models/book.rb
class Book < ActiveRecord::Base
	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks

	mount_uploader :image, ImageUploader
end
Book.import # for auto sync model with elastic search

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @title = "Books List"

    @books = Book.all

    respond_to do |format|
      format.html {render :index}
      format.json {render json: @books}
    end      
   
  end

  def show
  end

  def edit
  end

  def new
    @book = Book.new
  end

  def create
     @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: 'Book ' + @book.title + ' was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
     respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :pages, :image)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
	  if params[:q].nil?
	    @books = []
	  else
	    @books = Book.search params[:q]
	  end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper

	def edit_book_modal book
	  book_form_modal book
	end

	def book_form_modal book=Book.new
	  render partial: 'form', locals: {book: book}
	end	

	def new_book_modal
		book_form_modal
	end


end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/books/_form.html.erb
<button class="button_ok" data-toggle="modal" href='#modal-id'>Add Book</button>
<div class="modal fade" id="modal-id">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Book Administration</h4>
			</div>
			<div class="modal-body">

				<%= simple_form_for(book, html: { class: "form" }) do |f| %>

				<%= f.input :title , placeholder: 'Book Title' %>
				<%= f.input :description , placeholder: 'Book Description' %>
				<%= f.input :pages , placeholder: 'Pages Number' %>
				<%= f.file_field :image , placeholder: 'Load Fece Book', class: 'file-loading' %>

			</div>

			<div class="modal-footer">
				
				<div class="actions">
					<%= f.submit class: "button_ok" %>
				</div>

				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<div class="container">
	<h1>Books#edit</h1>


	<%= simple_form_for(@book, html: { class: "form" }) do |f| %>

	<%= f.input :title , placeholder: 'Book Title' %>
	<%= f.input :description , placeholder: 'Book Description' %>
	<%= f.input :pages , placeholder: 'Pages Number' %>

	<%= f.submit class: "button_ok" %>

	<% end %>
</div>

app/views/books/index.html.erb
<header>
	<h1><%= @title || "Book List" %></h1>
	<div class="header_sub">
		<%= new_book_modal %>
		<!-- <%= link_to 'Add Book', new_book_path  %>  -->
	</div>
</header>

<div class="container">
	<%= form_tag(search_path, :method => "get") do %>
	  <%= label_tag(:q, "Search for:") %>
	  <%= text_field_tag(:q) %>
	  <%= submit_tag("Search") %>
	<% end %>


	<% if flash[:notice] %>
	<div class="alert alert-success" role="alert" id="notice">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<%= flash[:notice] %>
	</div>
	<% end %>

	<% if @books.present? %>

	<% @books.each do |book| %>

	<div class="media">
		<div class="media-left media-middle">
			<%= image_tag book.image ,class: "img-thumbnail facebook"  %>
		</div>
		<div class="media-body">
			<h4 class="media-heading"><%= link_to book.title, book %></h4>
			<%= book.description %>
			Pages: <%= book.pages %>
		</div>
		<div class="pull-right">
			<%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' } %> | 
			<%= link_to "Edit", edit_book_path(book)  %> 
		</div>
	</div>
	

	<% end %>

	<% else %>
	<p>No content</p>
	<% end %>


</div>

app/views/books/new.html.erb
<%= form_for(@book) do |f| %>

<div class="field">
	<%= f.label :Title %><br>
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :Description %><br>
	<%= f.text_field :description %>
</div>
<div class="field">
	<%= f.label :Pages %><br>
	<%= f.text_field :pages %>
</div>
<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/books/show.html.erb
<div class="container">
	<h1>Detail View </h1>
	<hr>
	
	<% if flash[:notice] %>
	<div class="alert alert-success" role="alert" id="notice">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<%= flash[:notice] %>
	</div>
	<% end %>
	
	<div class="list-group">
		<ul>
			<li class="list-group-item"><h4><%= @book.title %></h4></li>
			<li class="list-group-item"><%= @book.description %></li>
			<li class="list-group-item">Pages: <%= @book.pages%></li>
		</ul>	
	</div>
	<%= link_to "Back", books_path  %>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Books</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/search.html.erb
<h1>Books Search</h1>
 
<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>
 
<ul>
  <% @books.each do |book| %>
    <li>
      <h3>
        <%= link_to book.title, controller: "books", action: "show", id: book._id%>
      </h3>
    </li>
  <% end %>
</ul>